name: MLOps
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
   
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: "Train my model"
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py 
          apt update
          apt upgrade
          apt -y  install apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          apt update
          apt-cache policy docker-ce
          apt -y install docker-ce
          curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version
          usermod -a -G docker "$(whoami)"
          newgrp docker
          service --status-all
          service docker start
          docker-compose ps
      
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker logs backend
      - name: Build the docker-compose stack
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Check logs
        run: docker logs backend
